sudo: required
services:
  - docker
before_install:
  - docker build -t lukasfrajt/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lukasfrajt/react-test  npm test -- --coverage

after_success:
  - docker build -t lukasfrajt/multi-client ./client
  - docker build -t lukasfrajt/multi-nginx ./nginx
  - docker build -t lukasfrajt/multi-server ./server
  - docker build -t lukasfrajt/multi-worker ./worker
  #LOGIN TO DOCKER CLI
  - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --pasword-stdin
  - docker push lukasfrajt/multi-client
  - docker push lukasfrajt/multi-nginx
  - docker push lukasfrajt/multi-server
  - docker push lukasfrajt/multi-worker



